version: "3.8"

services:
  mcp:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: mcp
    container_name: mcp
    volumes:
      - ..:/workspace:cached
    ports:
      - "3005:3005"
    command: sleep infinity
    env_file:
      - ../.env
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    user: node
